# Generated by Django 4.2.16 on 2024-10-03 11:56

from django.db import migrations
from django.utils import timezone


def create_initial_data(apps, schema_editor):
    Status = apps.get_model('tasks', 'Status')
    Board = apps.get_model('tasks', 'Board')
    Task = apps.get_model('tasks', 'Task')
    CustomUser = apps.get_model('accounts', 'CustomUser')

    to_do_status = Status.objects.create(name="To Do")
    in_progress_status = Status.objects.create(name="In Progress")
    done_status = Status.objects.create(name="Done")

    board_1 = Board.objects.create(
        name="Проект Alpha", description="Описание проекта Alpha")
    board_2 = Board.objects.create(
        name="Проект Beta", description="Описание проекта Beta")

    try:
        user = CustomUser.objects.first()
    except CustomUser.DoesNotExist:
        user = None

    Task.objects.create(
        board=board_1,
        title="Задача 1",
        description="Описание задачи 1",
        status=to_do_status,
        assigned_to=user,
        priority=1,
        due_date=timezone.now() + timezone.timedelta(days=5)
    )
    Task.objects.create(
        board=board_2,
        title="Задача 2",
        description="Описание задачи 2",
        status=in_progress_status,
        assigned_to=user,
        priority=2,
        due_date=timezone.now() + timezone.timedelta(days=10)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_tasks_task_status__0039af_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
